const KEY_COOKIES_USERNAME = 'cusername';
const KEY_COOKIES_PASSWORD = 'cpassword';
const KEY_STORAGE_DATACATATAN = 'cdatacatatan';

export {
  KEY_COOKIES_USERNAME,
  KEY_COOKIES_PASSWORD,
  KEY_STORAGE_DATACATATAN,
};
